/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideChat: typeof import('./src/components/Aside/aside-chat.vue')['default']
    AsideHeader: typeof import('./src/components/Aside/aside-header.vue')['default']
    BaseInputPassoword: typeof import('./src/components/Base/base-input-passoword.vue')['default']
    BaseInputPassword: typeof import('./src/components/Base/base-input-password.vue')['default']
    ChatContent: typeof import('./src/components/Chat/chat-content.vue')['default']
    ChatHeader: typeof import('./src/components/Chat/chat-header.vue')['default']
    ChatItem: typeof import('./src/components/Chat/chat-item.vue')['default']
    ChatItems: typeof import('./src/components/Chat/chat-item.vue')['default']
    ChatMessagePlace: typeof import('./src/components/Chat/chat-message-place.vue')['default']
    'Details.avatar': typeof import('./src/components/Details/details-avatar.vue')['default']
    DetailsAvatar: typeof import('./src/components/Details/details-avatar.vue')['default']
    DetailsHeader: typeof import('./src/components/Details/details-header.vue')['default']
    DetailsInfo: typeof import('./src/components/Details/details-info.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputPassword: typeof import('./src/components/Base/input-password.vue')['default']
    InputText: typeof import('./src/components/Base/input-text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
