name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Node.js версии 16 (если у вас JS/TS проект)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Запуск тестов
      - name: Run tests
        run: npm run test
