name: Deploy Docker container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh-add private_key
          # Ввод фразы-пароля
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add - <<< "${{ secrets.SSH_PASSPHRASE }}"

      - name: Deploy Docker container on server
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@91.147.92.135 "
            cd /opt/frontend/chat-lewis &&
            docker stop lewis-front || true &&
            docker rm lewis-front || true &&
            docker build -t lewis-front . &&
            docker run -d --name lewis-front -p 3000:80 lewis-front"
